// Generated by tools/bot_ml/phase8_fixture_contract.py. Do not edit.
#ifndef BOT_CALIBRATION_FIXTURE_CONTRACT_GENERATED_H
#define BOT_CALIBRATION_FIXTURE_CONTRACT_GENERATED_H

#include <array>
#include <cstdint>
#include <string_view>

namespace BotCalibrationFixtureContractGenerated
{
inline constexpr char Schema[] = "phase8_calibration_fixture_contract_v1";
inline constexpr char ContentSha256[] = "26e5cbdffd5587082be2da2a478fa70370c17d6cdbf5052a1c1e3b8d280c32f2";
inline constexpr char UpstreamRevision[] = "70d87383a9b92f30fb9e370c4676d3ce33b6e6b6";
inline constexpr uint32_t TargetEntry = 44548;
inline constexpr uint8_t TargetLevel = 88;
inline constexpr uint32_t TargetArmor = 11977;
inline constexpr uint32_t TargetCreatureType = 9;
inline constexpr uint32_t TargetMaxHealth = 1000000000;
inline constexpr uint32_t DurationMs = 300000;
inline constexpr float MeleeDistanceYards = 2.0f;
inline constexpr float RangedDistanceYards = 15.0f;

struct PowerContract
{
    char const* Spec;
    char const* UnitKind;
    char const* Name;
    uint8_t PowerType;
    bool Maximum;
    uint32_t ExactNativeValue;
};

struct SpecContract
{
    char const* Spec;
    char const* Lane;
    char const* SourceTestSha256;
    uint16_t PowerOffset;
    uint8_t PowerCount;
    uint8_t RunesReadyMask;
    uint8_t ComboPoints;
    bool NeutralEclipse;
    bool PetResourceRequired;
    uint16_t SetupAuraOffset;
    uint8_t SetupAuraCount;
    uint32_t FlaskItemId;
    uint32_t FlaskAuraSpellId;
    uint32_t FoodItemId;
    uint32_t FoodAuraSpellId;
    bool PetRuntimeProjectionComplete;
    float RuntimeMinimumDistanceYards;
    float RuntimeMaximumDistanceYards;
};

inline constexpr std::array<PowerContract, 25> PowerContracts = {{
    { "affliction_warlock", "player", "mana", 0, true, 0 } ,
    { "affliction_warlock", "player", "soul_shards", 7, true, 0 } ,
    { "affliction_warlock", "pet", "mana", 0, true, 0 } ,
    { "arms_warrior", "player", "rage", 1, false, 0 } ,
    { "assassination_rogue", "player", "energy", 3, true, 0 } ,
    { "balance_druid", "player", "mana", 0, true, 0 } ,
    { "balance_druid", "player", "eclipse", 8, false, 0 } ,
    { "combat_rogue", "player", "energy", 3, true, 0 } ,
    { "demonology_warlock", "player", "mana", 0, true, 0 } ,
    { "demonology_warlock", "player", "soul_shards", 7, true, 0 } ,
    { "demonology_warlock", "pet", "mana", 0, true, 0 } ,
    { "elemental_shaman", "player", "mana", 0, true, 0 } ,
    { "feral_druid_dps", "player", "energy", 3, true, 0 } ,
    { "fire_mage", "player", "mana", 0, true, 0 } ,
    { "frost_death_knight", "player", "runic_power", 6, false, 0 } ,
    { "fury_warrior", "player", "rage", 1, false, 0 } ,
    { "marksmanship_hunter", "player", "focus", 2, true, 0 } ,
    { "marksmanship_hunter", "pet", "focus", 2, true, 0 } ,
    { "retribution_paladin", "player", "mana", 0, true, 0 } ,
    { "retribution_paladin", "player", "holy_power", 9, false, 0 } ,
    { "shadow_priest", "player", "mana", 0, true, 0 } ,
    { "survival_hunter", "player", "focus", 2, true, 0 } ,
    { "survival_hunter", "pet", "focus", 2, true, 0 } ,
    { "unholy_death_knight", "player", "runic_power", 6, false, 1000 } ,
    { "unholy_death_knight", "pet", "energy", 3, true, 0 } ,
}};

inline constexpr std::array<uint32_t, 17> RequiredSetupAuraSpellIds = {{
    28176,
    2457,
    24858,
    28176,
    324,
    768,
    30482,
    48265,
    2458,
    13165,
    7294,
    31801,
    588,
    15473,
    13165,
    64420,
    48265,
}};

inline constexpr std::array<SpecContract, 16> SpecContracts = {{
    { "affliction_warlock", "short_ranged", "8f38bcba47d99fbac658ea0dba1ccfd11cd1703e5d66b26fec9f4368384d3d64", 0, 3, 0, 255, false, true, 0, 1, 58086, 79470, 0, 0, true, 7.5f, 8.5f } ,
    { "arms_warrior", "melee", "ab03ac6c2277f834fa6e5e6f5e07499a247ef9d6a4a3d0f510d6bc0282d307de", 3, 1, 0, 255, false, false, 1, 1, 58088, 79472, 0, 0, true, 2.0f, 3.2f } ,
    { "assassination_rogue", "melee", "03a96ae47e8f4548a31b86346ffdf1e0607d50fc1172a78b90112c8d8e12926d", 4, 1, 0, 0, false, false, 2, 0, 58087, 79471, 0, 0, true, 2.0f, 3.2f } ,
    { "balance_druid", "ranged", "b006fd31e0cea891eae20d3c9ce0b1fe8d9a4438f67d59f481c0ed1721c96384", 5, 2, 0, 255, true, false, 2, 1, 58086, 79470, 62671, 87547, true, 14.5f, 15.5f } ,
    { "combat_rogue", "melee", "fbb6d7e9288778f7558d077e5bf0becd342add9c2381af984f9d4d667e367543", 7, 1, 0, 0, false, false, 3, 0, 58087, 79471, 0, 0, true, 2.0f, 3.2f } ,
    { "demonology_warlock", "ranged", "394f11d9e26564e6a8c305a3544ddb6df883f826fa70e548c7a7ed391bd6ec4e", 8, 3, 0, 255, false, true, 3, 1, 58086, 79470, 0, 0, true, 14.5f, 15.5f } ,
    { "elemental_shaman", "ranged", "3307064f29e960f794c608cddc6a08d407b9e1851fced19e8067789d7f3ec13a", 11, 1, 0, 255, false, false, 4, 1, 58086, 79470, 0, 0, true, 14.5f, 15.5f } ,
    { "feral_druid_dps", "melee", "b93511634568697dc949a13f0b22f7efd96526daa58f0ec5992a5b8dcb1b387c", 12, 1, 0, 0, false, false, 5, 1, 58087, 79471, 0, 0, true, 2.0f, 3.2f } ,
    { "fire_mage", "ranged", "71a9228f45b0c57e464971f71a05d8af4588b274efd3d5711645d7012007afc7", 13, 1, 0, 255, false, false, 6, 1, 58086, 79470, 0, 0, true, 14.5f, 15.5f } ,
    { "frost_death_knight", "melee", "c43b8ea88f9654729c25425fcd3bf62dba5320e22983815b761214e3719d88dd", 14, 1, 63, 255, false, false, 7, 1, 58088, 79472, 0, 0, true, 2.0f, 3.2f } ,
    { "fury_warrior", "melee", "f77b34d99140388b71333886a1ed8c3e04869a77dd9052fcc1101d0b88f6fab7", 15, 1, 0, 255, false, false, 8, 1, 58088, 79472, 0, 0, true, 2.0f, 3.2f } ,
    { "marksmanship_hunter", "ranged", "e07dd1ec1662cadad96084a8720e935a2bc825259ac696a5d0c319b1767b432a", 16, 2, 0, 255, false, true, 9, 1, 58087, 79471, 0, 0, true, 14.5f, 15.5f } ,
    { "retribution_paladin", "melee", "b9461e1f452958d4c3c8bc7c512ed206b58df460905b16740489dd51d283c151", 18, 2, 0, 255, false, false, 10, 2, 58088, 79472, 0, 0, true, 2.0f, 3.2f } ,
    { "shadow_priest", "ranged", "528ff74616a6c6a279f5bd3e616fdfbaffc6a7c25c1476664497e42cedb159fb", 20, 1, 0, 255, false, false, 12, 2, 58086, 79470, 62290, 87547, true, 14.5f, 15.5f } ,
    { "survival_hunter", "ranged", "9706d97593a09a44731ceb2fa5216cf328dc1bc1aa5f40e8d581fab0ac403661", 21, 2, 0, 255, false, true, 14, 2, 58087, 79471, 0, 0, true, 14.5f, 15.5f } ,
    { "unholy_death_knight", "melee", "a23879b3c6e945289f8a635f85101f10834977dd8f138101a7726acf97db7f90", 23, 2, 63, 255, false, true, 16, 1, 58088, 79472, 0, 0, true, 2.0f, 3.2f } ,
}};

inline SpecContract const* FindSpec(std::string_view spec)
{
    for (SpecContract const& row : SpecContracts)
        if (spec == row.Spec)
            return &row;
    return nullptr;
}
}

#endif
