CREATE TABLE IF NOT EXISTS `bot_memory_pois` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `map_id` int unsigned NOT NULL,
  `zone_id` int unsigned NOT NULL,
  `area_id` int unsigned NOT NULL,
  `x` float NOT NULL,
  `y` float NOT NULL,
  `z` float NOT NULL,
  `poi_type` varchar(64) NOT NULL,
  `entity_guid` bigint unsigned NOT NULL DEFAULT '0',
  `entity_entry` int unsigned NOT NULL DEFAULT '0',
  `quest_id` int unsigned NOT NULL DEFAULT '0',
  `score` float NOT NULL DEFAULT '0',
  `discovered_at` datetime NOT NULL,
  `last_seen_at` datetime NOT NULL,
  `visit_count` int unsigned NOT NULL DEFAULT '0',
  `success_count` int unsigned NOT NULL DEFAULT '0',
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bot_poi_entity` (`bot_guid`, `poi_type`, `entity_guid`, `entity_entry`, `quest_id`),
  KEY `idx_bot_area` (`bot_guid`, `map_id`, `zone_id`, `area_id`),
  KEY `idx_poi_type` (`poi_type`, `entity_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bot_memory_failed_paths` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `map_id` int unsigned NOT NULL,
  `from_x` float NOT NULL,
  `from_y` float NOT NULL,
  `from_z` float NOT NULL,
  `to_x` float NOT NULL,
  `to_y` float NOT NULL,
  `to_z` float NOT NULL,
  `failure_type` varchar(64) NOT NULL,
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `last_failed_at` datetime NOT NULL,
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  KEY `idx_bot_map` (`bot_guid`, `map_id`),
  KEY `idx_failure_type` (`failure_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
