CREATE TABLE IF NOT EXISTS `bot_memory_objective_clusters` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `cluster_id` int unsigned NOT NULL,
  `map_id` int unsigned NOT NULL,
  `zone_id` int unsigned NOT NULL,
  `area_id` int unsigned NOT NULL,
  `quest_id` int unsigned NOT NULL DEFAULT '0',
  `objective_type` varchar(64) NOT NULL DEFAULT '',
  `completed_count` int unsigned NOT NULL DEFAULT '0',
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `blacklisted_until` datetime NULL,
  `last_result` varchar(64) NOT NULL DEFAULT '',
  `last_event_at` datetime NOT NULL,
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bot_cluster_quest` (`bot_guid`, `cluster_id`, `quest_id`, `objective_type`),
  KEY `idx_bot_zone` (`bot_guid`, `map_id`, `zone_id`),
  KEY `idx_blacklist` (`blacklisted_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bot_memory_recipe_sources` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `profession_skill_id` int unsigned NOT NULL DEFAULT '0',
  `recipe_spell_id` int unsigned NOT NULL,
  `source_type` varchar(64) NOT NULL,
  `source_entry` int unsigned NOT NULL DEFAULT '0',
  `item_id` int unsigned NOT NULL DEFAULT '0',
  `map_id` int unsigned NOT NULL DEFAULT '0',
  `zone_id` int unsigned NOT NULL DEFAULT '0',
  `area_id` int unsigned NOT NULL DEFAULT '0',
  `x` float NOT NULL DEFAULT '0',
  `y` float NOT NULL DEFAULT '0',
  `z` float NOT NULL DEFAULT '0',
  `reputation_required` int unsigned NOT NULL DEFAULT '0',
  `discovered_at` datetime NOT NULL,
  `last_seen_at` datetime NOT NULL,
  `success_count` int unsigned NOT NULL DEFAULT '0',
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bot_recipe_source` (`bot_guid`, `recipe_spell_id`, `source_type`, `source_entry`, `item_id`),
  KEY `idx_recipe` (`recipe_spell_id`),
  KEY `idx_source` (`source_type`, `source_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bot_memory_material_sources` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `item_id` int unsigned NOT NULL,
  `source_type` varchar(64) NOT NULL,
  `source_entry` int unsigned NOT NULL DEFAULT '0',
  `map_id` int unsigned NOT NULL DEFAULT '0',
  `zone_id` int unsigned NOT NULL DEFAULT '0',
  `area_id` int unsigned NOT NULL DEFAULT '0',
  `x` float NOT NULL DEFAULT '0',
  `y` float NOT NULL DEFAULT '0',
  `z` float NOT NULL DEFAULT '0',
  `drop_chance` float NOT NULL DEFAULT '0',
  `observed_count` int unsigned NOT NULL DEFAULT '0',
  `success_count` int unsigned NOT NULL DEFAULT '0',
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `last_seen_at` datetime NOT NULL,
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bot_material_source` (`bot_guid`, `item_id`, `source_type`, `source_entry`, `map_id`, `zone_id`, `area_id`),
  KEY `idx_item` (`item_id`),
  KEY `idx_source` (`source_type`, `source_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bot_memory_daily_cooldowns` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `cooldown_type` varchar(64) NOT NULL,
  `cooldown_key` varchar(128) NOT NULL,
  `spell_id` int unsigned NOT NULL DEFAULT '0',
  `item_id` int unsigned NOT NULL DEFAULT '0',
  `quest_id` int unsigned NOT NULL DEFAULT '0',
  `available_at` datetime NOT NULL,
  `last_used_at` datetime NULL,
  `use_count` int unsigned NOT NULL DEFAULT '0',
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bot_cooldown` (`bot_guid`, `cooldown_type`, `cooldown_key`),
  KEY `idx_available` (`available_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bot_memory_transport_usage` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `transport_type` varchar(64) NOT NULL,
  `transport_entry` int unsigned NOT NULL DEFAULT '0',
  `from_map_id` int unsigned NOT NULL DEFAULT '0',
  `from_zone_id` int unsigned NOT NULL DEFAULT '0',
  `to_map_id` int unsigned NOT NULL DEFAULT '0',
  `to_zone_id` int unsigned NOT NULL DEFAULT '0',
  `use_count` int unsigned NOT NULL DEFAULT '0',
  `success_count` int unsigned NOT NULL DEFAULT '0',
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `last_used_at` datetime NOT NULL,
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bot_transport` (`bot_guid`, `transport_type`, `transport_entry`, `from_map_id`, `from_zone_id`, `to_map_id`, `to_zone_id`),
  KEY `idx_transport` (`transport_type`, `transport_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bot_memory_decision_fingerprints` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bot_guid` int unsigned NOT NULL,
  `fingerprint_hash` int unsigned NOT NULL,
  `situation_type` varchar(64) NOT NULL,
  `action` varchar(64) NOT NULL,
  `activity` varchar(64) NOT NULL,
  `quest_id` int unsigned NOT NULL DEFAULT '0',
  `cluster_id` int unsigned NOT NULL DEFAULT '0',
  `map_id` int unsigned NOT NULL DEFAULT '0',
  `zone_id` int unsigned NOT NULL DEFAULT '0',
  `area_id` int unsigned NOT NULL DEFAULT '0',
  `repeat_count` int unsigned NOT NULL DEFAULT '0',
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `last_result` varchar(64) NOT NULL DEFAULT '',
  `first_seen_at` datetime NOT NULL,
  `last_seen_at` datetime NOT NULL,
  `metadata_json` mediumtext NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bot_fingerprint` (`bot_guid`, `fingerprint_hash`),
  KEY `idx_bot_recent` (`bot_guid`, `last_seen_at`),
  KEY `idx_loop_surface` (`situation_type`, `action`, `quest_id`, `cluster_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
