CREATE TABLE IF NOT EXISTS `bot_semantic_outcome_stats` (
  `entity_type` varchar(32) NOT NULL,
  `entity_key` int unsigned NOT NULL,
  `samples` int unsigned NOT NULL DEFAULT '0',
  `successes` int unsigned NOT NULL DEFAULT '0',
  `failures` int unsigned NOT NULL DEFAULT '0',
  `deaths` int unsigned NOT NULL DEFAULT '0',
  `total_reward` float NOT NULL DEFAULT '0',
  `total_power_delta` float NOT NULL DEFAULT '0',
  `avg_reward` float NOT NULL DEFAULT '0',
  `avg_power_delta` float NOT NULL DEFAULT '0',
  `danger_score` float NOT NULL DEFAULT '0',
  `progression_value` float NOT NULL DEFAULT '0',
  `last_experiment_id` bigint unsigned NULL,
  `last_run_id` bigint unsigned NULL,
  `last_event_type` varchar(64) NULL,
  `last_result` varchar(64) NULL,
  `features_json` text NULL,
  `embedding_json` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`entity_type`, `entity_key`),
  KEY `idx_bot_semantic_outcome_stats_danger` (`entity_type`, `danger_score`),
  KEY `idx_bot_semantic_outcome_stats_progression` (`entity_type`, `progression_value`),
  KEY `idx_bot_semantic_outcome_stats_run` (`last_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Learned semantic outcome stats and export-friendly embedding features for bot experiments';
