-- Canonical Phase 1 runtime-profile coverage for all 31 Cataclysm targets.
-- Explicit SQL/rule profiles remain authoritative; generic ML remains shadow-only.

INSERT INTO `bot_rotation_profile`
(`class_id`, `spec_tag`, `role`, `resource_type`, `range_band`, `movement_directive`, `auto_attack_mode`, `min_range`, `max_range`, `enabled`, `version`, `source_note`, `scope_note`) VALUES
(1, 'protection_warrior', 'tank', 'rage', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(2, 'protection', 'tank', 'mana_holy_power', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(6, 'blood_death_knight', 'tank', 'runes_runic_power', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(11, 'feral_druid_tank', 'tank', 'rage', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(2, 'holy_paladin', 'healer', 'mana_holy_power', 'ranged', 'healer_support', 'none', 0, 40, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(5, 'discipline_priest', 'healer', 'mana', 'ranged', 'healer_support', 'none', 0, 40, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(5, 'holy_priest', 'healer', 'mana', 'ranged', 'healer_support', 'none', 0, 40, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(7, 'restoration_shaman', 'healer', 'mana', 'ranged', 'healer_support', 'none', 0, 40, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(11, 'restoration_druid', 'healer', 'mana', 'ranged', 'healer_support', 'none', 0, 40, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(1, 'arms_warrior', 'dps', 'rage', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(1, 'fury_warrior', 'dps', 'rage', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(2, 'retribution_paladin', 'dps', 'mana_holy_power', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(3, 'beast_mastery_hunter', 'dps', 'focus', 'ranged', 'ranged', 'ranged', 5, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(3, 'marksmanship', 'dps', 'focus', 'ranged', 'ranged', 'ranged', 5, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(3, 'survival', 'dps', 'focus', 'ranged', 'ranged', 'ranged', 5, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(4, 'assassination_rogue', 'dps', 'energy', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(4, 'combat_rogue', 'dps', 'energy', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(4, 'subtlety_rogue', 'dps', 'energy', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(6, 'frost_death_knight', 'dps', 'runes_runic_power', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(6, 'unholy_death_knight', 'dps', 'runes_runic_power', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(7, 'elemental_shaman', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(7, 'enhancement', 'dps', 'mana_maelstrom', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(8, 'arcane_mage', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(8, 'fire', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(8, 'frost_mage', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(9, 'affliction_warlock', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(9, 'demonology_warlock', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(9, 'destruction_warlock', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(5, 'shadow_priest', 'dps', 'mana', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(11, 'balance_druid', 'dps', 'mana_eclipse', 'ranged', 'ranged', 'none', 0, 35, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target'),
(11, 'feral_druid_dps', 'dps', 'energy_combo_points', 'melee', 'melee', 'melee', 0, 5, 1, 2, 'all_spec_phase1_canonical_coverage', 'canonical all-spec target')
ON DUPLICATE KEY UPDATE
  `resource_type` = VALUES(`resource_type`),
  `range_band` = VALUES(`range_band`),
  `movement_directive` = VALUES(`movement_directive`),
  `auto_attack_mode` = VALUES(`auto_attack_mode`),
  `min_range` = VALUES(`min_range`),
  `max_range` = VALUES(`max_range`),
  `enabled` = VALUES(`enabled`),
  `version` = VALUES(`version`),
  `source_note` = VALUES(`source_note`),
  `scope_note` = VALUES(`scope_note`);

DELETE a FROM `bot_rotation_action` a
JOIN `bot_rotation_profile` p ON p.`id` = a.`profile_id`
WHERE (p.`class_id`, p.`spec_tag`, p.`role`) IN (
  (11, 'feral_druid_tank', 'tank'),
  (7, 'restoration_shaman', 'healer'),
  (1, 'arms_warrior', 'dps'),
  (1, 'fury_warrior', 'dps'),
  (2, 'retribution_paladin', 'dps'),
  (3, 'beast_mastery_hunter', 'dps'),
  (4, 'combat_rogue', 'dps'),
  (4, 'subtlety_rogue', 'dps'),
  (6, 'frost_death_knight', 'dps'),
  (6, 'unholy_death_knight', 'dps'),
  (8, 'arcane_mage', 'dps'),
  (8, 'frost_mage', 'dps'),
  (9, 'demonology_warlock', 'dps'),
  (9, 'destruction_warlock', 'dps'),
  (5, 'shadow_priest', 'dps'),
  (11, 'balance_druid', 'dps'),
  (11, 'feral_druid_dps', 'dps')
);

INSERT INTO `bot_rotation_action`
(`profile_id`, `sort_order`, `spell_id`, `category`, `mechanic_tags`, `damage_weight`, `threat_weight`, `mitigation_weight`, `survival_weight`, `priority_bucket`, `min_enemies`, `max_enemies`, `max_self_health_pct`, `requires_interruptible_target`, `requires_melee_range`, `target_selector`, `movement_directive`, `auto_attack_mode`, `maintain_aura_id`) VALUES
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_tank' AND `role`='tank'), 10, 6795, 'taunt', 'growl,taunt,threat_snap', 0, 4.00, 0, 0.30, 0, 1, 0, 1.00, 0, 0, 'enemy', 'melee', 'melee', 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_tank' AND `role`='tank'), 20, 22812, 'defensive', 'barkskin,self,mitigation', 0, 0, 0.90, 1.00, 1, 1, 0, 0.60, 0, 0, 'self', 'melee', 'melee', 22812),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_tank' AND `role`='tank'), 30, 33878, 'threat_build', 'mangle_bear,single_target,threat', 0.92, 1.00, 0, 0, 1, 1, 1, 1.00, 0, 1, 'enemy', 'melee', 'melee', 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_tank' AND `role`='tank'), 40, 33745, 'dot', 'lacerate,bleed,threat', 0.82, 0.90, 0, 0, 2, 1, 1, 1.00, 0, 1, 'enemy', 'melee', 'melee', 33745),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_tank' AND `role`='tank'), 50, 80313, 'spender', 'pulverize,lacerate_spender,mitigation', 0.88, 0.85, 0.25, 0.20, 2, 1, 1, 1.00, 0, 1, 'enemy', 'melee', 'melee', 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_tank' AND `role`='tank'), 60, 77758, 'aoe', 'thrash_bear,aoe,threat', 0.84, 1.00, 0, 0, 2, 2, 0, 1.00, 0, 1, 'enemy', 'melee', 'melee', 77758),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_tank' AND `role`='tank'), 70, 779, 'aoe', 'swipe_bear,aoe,threat', 0.76, 0.90, 0, 0, 3, 2, 0, 1.00, 0, 1, 'enemy', 'melee', 'melee', 0);

INSERT INTO `bot_rotation_action`
(`profile_id`, `sort_order`, `spell_id`, `category`, `mechanic_tags`, `healing_weight`, `survival_weight`, `priority_bucket`, `min_injured_players`, `injured_health_pct`, `target_selector`, `movement_directive`, `auto_attack_mode`, `max_range`, `maintain_aura_id`) VALUES
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=7 AND `spec_tag`='restoration_shaman' AND `role`='healer'), 10, 61295, 'heal_fast', 'riptide,hot,triage', 0.96, 0.75, 1, 1, 0.90, 'lowest_ally', 'healer_support', 'none', 40, 61295),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=7 AND `spec_tag`='restoration_shaman' AND `role`='healer'), 20, 77472, 'heal_fast', 'greater_healing_wave,large_heal', 1.00, 0.85, 1, 1, 0.60, 'lowest_ally', 'healer_support', 'none', 40, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=7 AND `spec_tag`='restoration_shaman' AND `role`='healer'), 30, 8004, 'heal_fast', 'healing_surge,emergency', 0.98, 0.90, 1, 1, 0.40, 'lowest_ally', 'healer_support', 'none', 40, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=7 AND `spec_tag`='restoration_shaman' AND `role`='healer'), 40, 1064, 'heal_aoe', 'chain_heal,party_heal', 0.90, 0.72, 2, 3, 0.82, 'lowest_ally', 'healer_support', 'none', 40, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=7 AND `spec_tag`='restoration_shaman' AND `role`='healer'), 50, 331, 'heal_efficient', 'healing_wave,efficient', 0.76, 0.60, 3, 1, 0.92, 'lowest_ally', 'healer_support', 'none', 40, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=7 AND `spec_tag`='restoration_shaman' AND `role`='healer'), 60, 51886, 'dispel_cleanse', 'cleanse_spirit,dispel', 0.20, 0.65, 1, 1, 1.00, 'lowest_ally', 'healer_support', 'none', 40, 0);

INSERT INTO `bot_rotation_action`
(`profile_id`, `sort_order`, `spell_id`, `category`, `mechanic_tags`, `damage_weight`, `survival_weight`, `priority_bucket`, `min_enemies`, `max_enemies`, `max_target_health_pct`, `requires_interruptible_target`, `requires_melee_range`, `requires_ranged_range`, `target_selector`, `movement_directive`, `auto_attack_mode`, `min_range`, `max_range`, `maintain_aura_id`) VALUES
-- Arms Warrior
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='arms_warrior' AND `role`='dps'), 10, 6552, 'interrupt', 'pummel,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='arms_warrior' AND `role`='dps'), 20, 772, 'dot', 'rend,bleed', 0.92, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 772),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='arms_warrior' AND `role`='dps'), 30, 86346, 'debuff', 'colossus_smash,armor_debuff', 1.00, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 86346),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='arms_warrior' AND `role`='dps'), 40, 12294, 'spender', 'mortal_strike,primary', 0.98, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='arms_warrior' AND `role`='dps'), 50, 7384, 'spender', 'overpower,proc', 0.90, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='arms_warrior' AND `role`='dps'), 60, 5308, 'execute', 'execute,low_health', 1.00, 0, 1, 1, 1, 0.20, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='arms_warrior' AND `role`='dps'), 70, 1464, 'builder', 'slam,filler', 0.72, 0, 4, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
-- Fury Warrior
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='fury_warrior' AND `role`='dps'), 10, 6552, 'interrupt', 'pummel,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='fury_warrior' AND `role`='dps'), 20, 86346, 'debuff', 'colossus_smash,armor_debuff', 1.00, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 86346),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='fury_warrior' AND `role`='dps'), 30, 23881, 'resource_generator', 'bloodthirst,primary', 0.98, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='fury_warrior' AND `role`='dps'), 40, 85288, 'spender', 'raging_blow,enrage', 0.94, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='fury_warrior' AND `role`='dps'), 50, 5308, 'execute', 'execute,low_health', 1.00, 0, 1, 1, 1, 0.20, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='fury_warrior' AND `role`='dps'), 60, 1680, 'aoe', 'whirlwind,aoe', 0.86, 0, 2, 2, 0, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=1 AND `spec_tag`='fury_warrior' AND `role`='dps'), 70, 1464, 'builder', 'slam,proc_filler', 0.70, 0, 4, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
-- Retribution Paladin
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=2 AND `spec_tag`='retribution_paladin' AND `role`='dps'), 10, 96231, 'interrupt', 'rebuke,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=2 AND `spec_tag`='retribution_paladin' AND `role`='dps'), 20, 35395, 'resource_generator', 'crusader_strike,holy_power', 0.94, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=2 AND `spec_tag`='retribution_paladin' AND `role`='dps'), 30, 85256, 'spender', 'templars_verdict,holy_power', 1.00, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=2 AND `spec_tag`='retribution_paladin' AND `role`='dps'), 40, 20271, 'builder', 'judgement,ranged_filler', 0.82, 0, 2, 1, 1, 1.00, 0, 0, 0, 'enemy', 'melee', 'melee', 0, 30, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=2 AND `spec_tag`='retribution_paladin' AND `role`='dps'), 50, 879, 'spender', 'exorcism,proc', 0.88, 0, 2, 1, 1, 1.00, 0, 0, 0, 'enemy', 'melee', 'melee', 0, 30, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=2 AND `spec_tag`='retribution_paladin' AND `role`='dps'), 60, 24275, 'execute', 'hammer_of_wrath,execute', 1.00, 0, 1, 1, 1, 0.20, 0, 0, 1, 'enemy', 'melee', 'melee', 0, 30, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=2 AND `spec_tag`='retribution_paladin' AND `role`='dps'), 70, 53385, 'aoe', 'divine_storm,aoe', 0.90, 0, 2, 2, 0, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
-- Beast Mastery Hunter
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=3 AND `spec_tag`='beast_mastery_hunter' AND `role`='dps'), 10, 1978, 'dot', 'serpent_sting,dot', 0.86, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'ranged', 5, 35, 1978),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=3 AND `spec_tag`='beast_mastery_hunter' AND `role`='dps'), 20, 34026, 'spender', 'kill_command,pet_primary', 1.00, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'ranged', 5, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=3 AND `spec_tag`='beast_mastery_hunter' AND `role`='dps'), 30, 53351, 'execute', 'kill_shot,execute', 1.00, 0, 1, 1, 1, 0.20, 0, 0, 1, 'enemy', 'ranged', 'ranged', 5, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=3 AND `spec_tag`='beast_mastery_hunter' AND `role`='dps'), 40, 3044, 'spender', 'arcane_shot,focus_dump', 0.82, 0, 3, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'ranged', 5, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=3 AND `spec_tag`='beast_mastery_hunter' AND `role`='dps'), 50, 77767, 'resource_generator', 'cobra_shot,focus_builder', 0.74, 0, 4, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'ranged', 5, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=3 AND `spec_tag`='beast_mastery_hunter' AND `role`='dps'), 60, 2643, 'aoe', 'multi_shot,aoe', 0.88, 0, 2, 3, 0, 1.00, 0, 0, 1, 'enemy', 'ranged', 'ranged', 5, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=3 AND `spec_tag`='beast_mastery_hunter' AND `role`='dps'), 70, 19577, 'stun_cc', 'intimidation,pet_control', 0.30, 0.30, 3, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'ranged', 5, 35, 0),
-- Combat Rogue
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 10, 1766, 'interrupt', 'kick,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 20, 84617, 'builder', 'revealing_strike,debuff', 0.86, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 84617),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 30, 1752, 'builder', 'sinister_strike,combo_builder', 0.88, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 40, 5171, 'buff', 'slice_and_dice,self,haste', 0.84, 0.20, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 5171),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 50, 1943, 'dot', 'rupture,bleed', 0.82, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 1943),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 60, 2098, 'spender', 'eviscerate,combo_spender', 0.90, 0, 3, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 70, 13750, 'offensive_cooldown', 'adrenaline_rush,energy', 0.88, 0, 2, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 13750),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='combat_rogue' AND `role`='dps'), 80, 51690, 'offensive_cooldown', 'killing_spree,burst', 0.94, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
-- Subtlety Rogue
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='subtlety_rogue' AND `role`='dps'), 10, 1766, 'interrupt', 'kick,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='subtlety_rogue' AND `role`='dps'), 20, 16511, 'builder', 'hemorrhage,bleed_debuff', 0.88, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 16511),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='subtlety_rogue' AND `role`='dps'), 30, 53, 'builder', 'backstab,positional', 0.94, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='subtlety_rogue' AND `role`='dps'), 40, 5171, 'buff', 'slice_and_dice,self,haste', 0.84, 0.20, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 5171),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='subtlety_rogue' AND `role`='dps'), 50, 1943, 'dot', 'rupture,bleed', 0.86, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 1943),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='subtlety_rogue' AND `role`='dps'), 60, 2098, 'spender', 'eviscerate,combo_spender', 0.90, 0, 3, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=4 AND `spec_tag`='subtlety_rogue' AND `role`='dps'), 70, 51713, 'offensive_cooldown', 'shadow_dance,burst', 0.94, 0, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 51713),
-- Frost Death Knight
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 10, 57330, 'buff', 'horn_of_winter,self,prepull', 0.20, 0.20, 0, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 57330),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 20, 48266, 'buff', 'frost_presence,self', 0.20, 0.20, 0, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 48266),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 30, 47528, 'interrupt', 'mind_freeze,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 40, 51271, 'offensive_cooldown', 'pillar_of_frost,burst', 0.94, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 51271),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 50, 49184, 'aoe', 'howling_blast,frost_fever,aoe', 0.92, 0, 1, 2, 0, 1.00, 0, 0, 0, 'enemy', 'melee', 'melee', 0, 30, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 60, 49020, 'spender', 'obliterate,runes', 0.98, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 70, 49143, 'spender', 'frost_strike,runic_power', 0.90, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='frost_death_knight' AND `role`='dps'), 80, 45462, 'dot', 'plague_strike,blood_plague', 0.72, 0, 3, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 45462),
-- Unholy Death Knight
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 10, 57330, 'buff', 'horn_of_winter,self,prepull', 0.20, 0.20, 0, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 57330),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 20, 46584, 'buff', 'raise_dead,permanent_ghoul', 0.30, 0.40, 0, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 30, 47528, 'interrupt', 'mind_freeze,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 40, 77575, 'debuff', 'outbreak,diseases', 0.90, 0, 1, 1, 1, 1.00, 0, 0, 0, 'enemy', 'melee', 'melee', 0, 30, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 50, 85948, 'resource_generator', 'festering_strike,disease_extension', 0.90, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 60, 55090, 'spender', 'scourge_strike,primary', 1.00, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 70, 47541, 'spender', 'death_coil,runic_power', 0.86, 0, 3, 1, 1, 1.00, 0, 0, 0, 'enemy', 'melee', 'melee', 0, 30, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=6 AND `spec_tag`='unholy_death_knight' AND `role`='dps'), 80, 63560, 'offensive_cooldown', 'dark_transformation,ghoul', 0.94, 0, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 63560),
-- Arcane Mage
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='arcane_mage' AND `role`='dps'), 10, 2139, 'interrupt', 'counterspell,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='arcane_mage' AND `role`='dps'), 20, 12042, 'offensive_cooldown', 'arcane_power,burn_phase', 1.00, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 12042),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='arcane_mage' AND `role`='dps'), 30, 30451, 'builder', 'arcane_blast,primary', 0.98, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='arcane_mage' AND `role`='dps'), 40, 5143, 'spender', 'arcane_missiles,proc', 0.92, 0, 2, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='arcane_mage' AND `role`='dps'), 50, 44425, 'spender', 'arcane_barrage,movement', 0.84, 0, 3, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='arcane_mage' AND `role`='dps'), 60, 1449, 'aoe', 'arcane_explosion,aoe', 0.86, 0, 2, 3, 0, 1.00, 0, 0, 0, 'enemy', 'ranged', 'none', 0, 10, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='arcane_mage' AND `role`='dps'), 70, 12051, 'buff', 'evocation,mana_recovery', 0, 0.60, 2, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 0),
-- Frost Mage
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 10, 2139, 'interrupt', 'counterspell,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 20, 31687, 'buff', 'summon_water_elemental,pet', 0.30, 0.30, 0, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 30, 12472, 'offensive_cooldown', 'icy_veins,haste', 0.94, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 12472),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 40, 44572, 'spender', 'deep_freeze,fingers_of_frost', 1.00, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 50, 44614, 'spender', 'frostfire_bolt,brain_freeze', 0.92, 0, 2, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 60, 30455, 'spender', 'ice_lance,movement_proc', 0.84, 0, 3, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 70, 116, 'builder', 'frostbolt,filler', 0.78, 0, 4, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=8 AND `spec_tag`='frost_mage' AND `role`='dps'), 80, 10, 'aoe', 'blizzard,aoe', 0.86, 0, 2, 3, 0, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
-- Demonology Warlock
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 10, 47241, 'offensive_cooldown', 'metamorphosis,burst', 1.00, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 47241),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 20, 77801, 'offensive_cooldown', 'demon_soul,pet_burst', 0.96, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 77801),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 30, 348, 'dot', 'immolate,dot', 0.90, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 348),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 40, 172, 'dot', 'corruption,dot', 0.86, 0, 2, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 172),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 50, 71521, 'spender', 'hand_of_guldan,primary', 1.00, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 60, 6353, 'execute', 'soul_fire,decimation', 0.94, 0, 2, 1, 1, 0.25, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 70, 686, 'builder', 'shadow_bolt,filler', 0.76, 0, 4, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='demonology_warlock' AND `role`='dps'), 80, 1949, 'aoe', 'hellfire,aoe', 0.86, 0.20, 2, 3, 0, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 10, 0),
-- Destruction Warlock
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 10, 77801, 'offensive_cooldown', 'demon_soul,pet_burst', 0.96, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 77801),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 20, 348, 'dot', 'immolate,dot', 0.94, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 348),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 30, 17962, 'spender', 'conflagrate,immolate', 1.00, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 40, 50796, 'spender', 'chaos_bolt,primary', 0.96, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 50, 6353, 'buff', 'soul_fire,improved_soul_fire', 0.90, 0, 2, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 60, 17877, 'execute', 'shadowburn,execute', 1.00, 0, 1, 1, 1, 0.20, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 70, 29722, 'builder', 'incinerate,filler', 0.80, 0, 4, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=9 AND `spec_tag`='destruction_warlock' AND `role`='dps'), 80, 5740, 'aoe', 'rain_of_fire,aoe', 0.86, 0, 2, 3, 0, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
-- Shadow Priest
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 10, 589, 'dot', 'shadow_word_pain,dot', 0.92, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 589),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 20, 34914, 'dot', 'vampiric_touch,dot', 0.96, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 34914),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 30, 2944, 'dot', 'devouring_plague,dot', 0.94, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 2944),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 40, 8092, 'spender', 'mind_blast,orb_spender', 1.00, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 50, 32379, 'execute', 'shadow_word_death,execute', 0.98, 0, 1, 1, 1, 0.25, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 60, 15407, 'builder', 'mind_flay,filler', 0.82, 0, 4, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 70, 48045, 'aoe', 'mind_sear,aoe', 0.88, 0, 2, 3, 0, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=5 AND `spec_tag`='shadow_priest' AND `role`='dps'), 80, 47585, 'defensive', 'dispersion,self,mana,mitigation', 0, 1.00, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 47585),
-- Balance Druid
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 10, 8921, 'dot', 'moonfire,dot', 0.92, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 8921),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 20, 5570, 'dot', 'insect_swarm,dot', 0.92, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 5570),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 30, 78674, 'spender', 'starsurge,primary', 1.00, 0, 1, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 40, 33831, 'offensive_cooldown', 'force_of_nature,treants', 0.90, 0, 2, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 50, 48505, 'offensive_cooldown', 'starfall,aoe_burst', 0.94, 0, 1, 2, 0, 1.00, 0, 0, 0, 'self', 'ranged', 'none', 0, 0, 48505),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 60, 2912, 'builder', 'starfire,eclipse', 0.82, 0, 3, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 70, 5176, 'builder', 'wrath,eclipse', 0.80, 0, 3, 1, 1, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='balance_druid' AND `role`='dps'), 80, 16914, 'aoe', 'hurricane,aoe', 0.84, 0, 2, 3, 0, 1.00, 0, 0, 1, 'enemy', 'ranged', 'none', 0, 35, 0),
-- Feral DPS Druid
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 10, 80965, 'interrupt', 'skull_bash,interrupt', 0.15, 0.20, 1, 1, 0, 1.00, 1, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 20, 5217, 'offensive_cooldown', 'tigers_fury,energy', 0.90, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 5217),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 30, 50334, 'offensive_cooldown', 'berserk,burst', 0.96, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 50334),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 40, 1822, 'dot', 'rake,bleed', 0.94, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 1822),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 50, 1079, 'dot', 'rip,finisher_bleed', 1.00, 0, 1, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 1079),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 60, 52610, 'buff', 'savage_roar,self,finisher', 0.94, 0.10, 1, 1, 1, 1.00, 0, 0, 0, 'self', 'melee', 'melee', 0, 0, 52610),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 70, 33876, 'builder', 'mangle_cat,bleed_debuff', 0.88, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 33876),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 80, 5221, 'builder', 'shred,combo_builder', 0.92, 0, 2, 1, 1, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 90, 22568, 'execute', 'ferocious_bite,finisher', 0.90, 0, 2, 1, 1, 0.25, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0),
((SELECT `id` FROM `bot_rotation_profile` WHERE `class_id`=11 AND `spec_tag`='feral_druid_dps' AND `role`='dps'), 100, 62078, 'aoe', 'swipe_cat,aoe', 0.86, 0, 2, 3, 0, 1.00, 0, 1, 0, 'enemy', 'melee', 'melee', 0, 5, 0);
