from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

try:
    from .common import stable_hash, write_json
except ImportError:
    from common import stable_hash, write_json


ROLE_REQUIREMENTS = {
    "stonecore_5n": {"tank": 1, "healer": 1, "dps": 3},
    "blackwing_descent_10n": {"tank": 2, "healer": 3, "dps": 5},
}

REQUIRED_EQUIPMENT_SLOTS = [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

ACTION_PROFILE_SPELLS_BY_CLASS = {
    1: [78, 100, 355, 2565, 6552],
    2: [20271, 35395, 635, 19750, 62124, 96231],
    3: [75, 1978, 3044],
    4: [1752, 2098, 1766, 408],
    5: [585, 589, 2061, 2050, 596, 527],
    6: [45477, 45462, 47541, 47528, 56222],
    7: [403, 8050, 331, 8004, 57994],
    8: [133, 44614, 11366, 2136, 2139, 45438],
    9: [686, 172, 348, 17962],
    11: [5176, 8921, 8936, 5185, 80965],
}


def sql_quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def load_config(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_gear_profiles(path: Path | None) -> dict[str, Any]:
    if not path or not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload.get("profiles", {})


def apply_gear_profiles(config: dict[str, Any], profiles: dict[str, Any]) -> dict[str, Any]:
    if not profiles:
        return config
    copied = json.loads(json.dumps(config))
    for scenario in copied["scenarios"]:
        for bot in scenario["bots"]:
            if bot.get("equipment"):
                continue
            profile = profiles.get(str(bot.get("class_spec") or ""))
            if profile:
                bot["equipment"] = profile.get("equipment", [])
                bot["gear_profile"] = str(bot.get("class_spec") or "")
    return copied


def character_names(config: dict[str, Any]) -> list[str]:
    return [str(bot["name"]) for scenario in config["scenarios"] for bot in scenario["bots"]]


def account_commands(config: dict[str, Any]) -> str:
    password = config.get("account_password", "validation")
    lines = [
        "# Apply these in worldserver console before provision_characters.sql if accounts do not exist.",
        "# The SQL uses account usernames as stable selectors and does not store account password hashes.",
    ]
    for name in sorted({str(bot["account"]).upper() for scenario in config["scenarios"] for bot in scenario["bots"]}):
        lines.append(f"account create {name} {password}")
        lines.append(f"account set addon {name} 3")
    return "\n".join(lines) + "\n"


def srp6_registration_data(username: str, password: str) -> tuple[bytes, bytes]:
    normalized_username = username.upper()
    normalized_password = password.upper()
    salt = hashlib.sha256(f"trinity-cata-validation-account:{normalized_username}:{normalized_password}".encode("utf-8")).digest()
    inner = hashlib.sha1(f"{normalized_username}:{normalized_password}".encode("utf-8")).digest()
    exponent = int.from_bytes(hashlib.sha1(salt + inner).digest(), "little")
    modulus = int("894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7", 16)
    verifier = pow(7, exponent, modulus).to_bytes(32, "little")
    return salt, verifier


def sql_binary_literal(value: bytes) -> str:
    return "X'" + value.hex() + "'"


def build_account_insert_sql(config: dict[str, Any]) -> str:
    password = config.get("account_password", "validation")
    lines = [
        "-- Generated by tools.bot_ml.build_validation_provisioning.",
        "-- Creates only missing validation accounts with deterministic SRP6 credentials for reproducible local validation.",
        "-- Existing account passwords are not overwritten; expansion is kept at Cataclysm or higher.",
    ]
    for username in sorted({str(bot["account"]).upper() for scenario in config["scenarios"] for bot in scenario["bots"]}):
        salt, verifier = srp6_registration_data(username, password)
        lines.append(
            "INSERT INTO `auth`.`account` (`username`, `salt`, `verifier`, `reg_mail`, `email`, `joindate`, `expansion`) "
            f"VALUES ({sql_quote(username)}, {sql_binary_literal(salt)}, {sql_binary_literal(verifier)}, '', '', NOW(), 3) "
            "ON DUPLICATE KEY UPDATE `expansion` = GREATEST(`expansion`, VALUES(`expansion`));"
        )
    return "\n".join(lines) + "\n"


def bot_guid_expression(name: str) -> str:
    return f"(SELECT `guid` FROM `characters`.`characters` WHERE `name` = {sql_quote(name)} LIMIT 1)"


def bot_spell_ids(bot: dict[str, Any]) -> list[int]:
    configured = [int(spell) for spell in bot.get("spells", [])]
    profile_spells = ACTION_PROFILE_SPELLS_BY_CLASS.get(int(bot.get("class", 0)), [])
    return sorted({spell for spell in configured + profile_spells if spell > 0})


def build_character_insert_sql(config: dict[str, Any]) -> str:
    lines = [
        "-- Generated by tools.bot_ml.build_validation_provisioning.",
        "-- Review before applying. This resets only configured validation character names and deterministic item GUID ranges.",
        "UPDATE `characters`.`characters` SET `online` = 0 WHERE `name` IN (" + ", ".join(sql_quote(name) for name in character_names(config)) + ");",
    ]
    item_guid_base = int(config.get("item_guid_base", 9700000))
    item_guid_limit = item_guid_base + 100000
    lines.append(f"DELETE FROM `characters`.`character_inventory` WHERE `item` >= {item_guid_base} AND `item` < {item_guid_limit};")
    lines.append(f"DELETE FROM `characters`.`item_instance` WHERE `guid` >= {item_guid_base} AND `guid` < {item_guid_limit};")
    lines.append("DELETE FROM `characters`.`character_bot_pool` WHERE `guid` IN (SELECT `guid` FROM `characters`.`characters` WHERE `name` IN (" + ", ".join(sql_quote(name) for name in character_names(config)) + "));")
    lines.append("DELETE FROM `characters`.`character_glyphs` WHERE `guid` IN (SELECT `guid` FROM `characters`.`characters` WHERE `name` IN (" + ", ".join(sql_quote(name) for name in character_names(config)) + "));")
    lines.append("DELETE FROM `characters`.`character_skills` WHERE `guid` IN (SELECT `guid` FROM `characters`.`characters` WHERE `name` IN (" + ", ".join(sql_quote(name) for name in character_names(config)) + "));")
    lines.append("DELETE FROM `characters`.`character_spell` WHERE `guid` IN (SELECT `guid` FROM `characters`.`characters` WHERE `name` IN (" + ", ".join(sql_quote(name) for name in character_names(config)) + "));")
    lines.append("DELETE FROM `characters`.`characters` WHERE `name` IN (" + ", ".join(sql_quote(name) for name in character_names(config)) + ");")

    item_guid = item_guid_base
    for scenario in config["scenarios"]:
        start = scenario["start_position"]
        tag = scenario["id"]
        for slot, bot in enumerate(scenario["bots"]):
            name = str(bot["name"])
            account = str(bot["account"]).upper()
            role = str(bot["role"])
            class_spec = str(bot.get("class_spec") or bot.get("class") or role)
            lines.append(
                "INSERT INTO `characters`.`characters` "
                "(`guid`, `account`, `name`, `slot`, `race`, `class`, `gender`, `level`, `xp`, `money`, `position_x`, `position_y`, `position_z`, `map`, `orientation`, `taximask`, `online`, `cinematic`, `totaltime`, `leveltime`, `logout_time`, `health`, `power1`, `talentGroupsCount`, `activeTalentGroup`, `equipmentCache`) "
                f"SELECT COALESCE(MAX(c.`guid`), 0) + 1, a.`id`, {sql_quote(name)}, {slot}, {int(bot['race'])}, {int(bot['class'])}, {int(bot.get('gender', 0))}, {int(bot.get('level', 85))}, 0, {int(bot.get('money', config.get('default_money', 10000000)))}, "
                f"{float(start['x'])}, {float(start['y'])}, {float(start['z'])}, {int(start['map_id'])}, {float(start.get('o', 0.0))}, '', 0, 1, 0, 0, 0, 100, 100, 1, 0, '' "
                f"FROM `auth`.`account` a LEFT JOIN `characters`.`characters` c ON 1 = 1 WHERE a.`username` = {sql_quote(account)} GROUP BY a.`id`;"
            )
            lines.append(
                "INSERT INTO `characters`.`character_bot_pool` (`guid`, `role`, `class_spec`, `enabled`, `in_use`, `experiment_tags`, `notes`) "
                f"SELECT c.`guid`, {sql_quote(role)}, {sql_quote(class_spec)}, 1, 0, {sql_quote(tag)}, {sql_quote('validation_provisioning')} FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)} "
                "ON DUPLICATE KEY UPDATE `role` = VALUES(`role`), `class_spec` = VALUES(`class_spec`), `enabled` = 1, `in_use` = 0, `experiment_tags` = VALUES(`experiment_tags`), `notes` = VALUES(`notes`);"
            )
            for skill in bot.get("skills", config.get("default_skills", [])):
                lines.append(
                    "INSERT INTO `characters`.`character_skills` (`guid`, `skill`, `value`, `max`) "
                    f"SELECT c.`guid`, {int(skill['id'])}, {int(skill.get('value', 525))}, {int(skill.get('max', 525))} FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)} "
                    "ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), `max` = VALUES(`max`);"
                )
            for spell_id in bot_spell_ids(bot):
                lines.append(
                    "INSERT INTO `characters`.`character_spell` (`guid`, `spell`, `active`, `disabled`) "
                    f"SELECT c.`guid`, {spell_id}, 1, 0 FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)} "
                    "ON DUPLICATE KEY UPDATE `active` = VALUES(`active`), `disabled` = VALUES(`disabled`);"
                )
            glyphs = list(bot.get("glyphs", []))[:9]
            if glyphs:
                glyph_values = glyphs + [0] * (9 - len(glyphs))
                lines.append(
                    "INSERT INTO `characters`.`character_glyphs` (`guid`, `talentGroup`, `glyph1`, `glyph2`, `glyph3`, `glyph4`, `glyph5`, `glyph6`, `glyph7`, `glyph8`, `glyph9`) "
                    f"SELECT c.`guid`, 0, {', '.join(str(int(value)) for value in glyph_values)} FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)} "
                    "ON DUPLICATE KEY UPDATE `glyph1` = VALUES(`glyph1`), `glyph2` = VALUES(`glyph2`), `glyph3` = VALUES(`glyph3`), `glyph4` = VALUES(`glyph4`), `glyph5` = VALUES(`glyph5`), `glyph6` = VALUES(`glyph6`), `glyph7` = VALUES(`glyph7`), `glyph8` = VALUES(`glyph8`), `glyph9` = VALUES(`glyph9`);"
                )
            for item in bot.get("equipment", []):
                item_guid += 1
                lines.append(
                    "INSERT INTO `characters`.`item_instance` (`guid`, `itemEntry`, `owner_guid`, `creatorGuid`, `giftCreatorGuid`, `count`, `duration`, `charges`, `flags`, `enchantments`, `randomPropertyType`, `randomPropertyId`, `durability`, `creationTime`, `text`) "
                    f"SELECT {item_guid}, {int(item['item_id'])}, c.`guid`, 0, 0, 1, 0, '', 0, {sql_quote(str(item.get('enchantments', '')))}, 0, 0, {int(item.get('durability', 100))}, UNIX_TIMESTAMP(), '' FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)};"
                )
                lines.append(
                    "INSERT INTO `characters`.`character_inventory` (`guid`, `bag`, `slot`, `item`) "
                    f"SELECT c.`guid`, 0, {int(item['slot'])}, {item_guid} FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)};"
                )
            for consumable in bot.get("consumables", config.get("default_consumables", [])):
                item_guid += 1
                lines.append(
                    "INSERT INTO `characters`.`item_instance` (`guid`, `itemEntry`, `owner_guid`, `creatorGuid`, `giftCreatorGuid`, `count`, `duration`, `charges`, `flags`, `enchantments`, `randomPropertyType`, `randomPropertyId`, `durability`, `creationTime`, `text`) "
                    f"SELECT {item_guid}, {int(consumable['item_id'])}, c.`guid`, 0, 0, {int(consumable.get('count', 20))}, 0, '', 0, '', 0, 0, 1, UNIX_TIMESTAMP(), '' FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)};"
                )
                lines.append(
                    "INSERT INTO `characters`.`character_inventory` (`guid`, `bag`, `slot`, `item`) "
                    f"SELECT c.`guid`, 0, {int(consumable['slot'])}, {item_guid} FROM `characters`.`characters` c WHERE c.`name` = {sql_quote(name)};"
                )
    lines.append("UPDATE `characters`.`character_bot_pool` SET `in_use` = 0 WHERE `experiment_tags` IN (" + ", ".join(sql_quote(str(s["id"])) for s in config["scenarios"]) + ");")
    return "\n".join(lines) + "\n"


def role_counts(bots: list[dict[str, Any]]) -> dict[str, int]:
    counts = {"tank": 0, "healer": 0, "dps": 0}
    for bot in bots:
        role = str(bot.get("role", "dps"))
        counts[role] = counts.get(role, 0) + 1
    return counts


def scenario_report(config: dict[str, Any]) -> dict[str, Any]:
    scenarios = []
    for scenario in config["scenarios"]:
        bots = scenario["bots"]
        required_roles = ROLE_REQUIREMENTS.get(str(scenario["id"]), {})
        counts = role_counts(bots)
        role_ok = all(counts.get(role, 0) >= count for role, count in required_roles.items())
        max_level_ok = all(int(bot.get("level", 0)) >= int(config.get("max_level", 85)) for bot in bots)
        skills_ok = all(bool(bot.get("skills") or config.get("default_skills")) for bot in bots)
        spells_ok = all(bool(bot_spell_ids(bot)) for bot in bots)
        glyphs_ok = all(len(bot.get("glyphs", [])) >= 3 for bot in bots)
        consumables_ok = all(bool(bot.get("consumables") or config.get("default_consumables")) for bot in bots)
        gear_missing = {
            bot["name"]: sorted(set(REQUIRED_EQUIPMENT_SLOTS) - {int(item.get("slot", -1)) for item in bot.get("equipment", [])})
            for bot in bots
        }
        gear_ok = all(not missing for missing in gear_missing.values())
        gems_ok = all(all(not item.get("socket_colors") or item.get("gem_item_ids") for item in bot.get("equipment", [])) for bot in bots)
        enchants_ok = all(all(int(item.get("enchant_id") or 0) for item in bot.get("equipment", [])) for bot in bots)
        missing = []
        if not role_ok:
            missing.append("role_coverage")
        if not max_level_ok:
            missing.append("max_level")
        if not skills_ok:
            missing.append("full_skills")
        if not spells_ok:
            missing.append("class_spec_spells")
        if not glyphs_ok:
            missing.append("glyphs")
        if not consumables_ok:
            missing.append("consumables")
        if not gear_ok:
            missing.append("complete_equipment_slots")
        if gear_ok and not gems_ok:
            missing.append("gems")
        if gear_ok and not enchants_ok:
            missing.append("enchants")
        scenarios.append(
            {
                "scenario_id": scenario["id"],
                "bot_count": len(bots),
                "role_counts": counts,
                "required_roles": required_roles,
                "ready": not missing,
                "missing": missing,
                "gear_missing_slots": gear_missing,
                "gear_profiles": {bot["name"]: bot.get("gear_profile", "") for bot in bots},
                "start_position": scenario["start_position"],
            }
        )
    return {
        "schema": "bot_validation_provisioning_report_v1",
        "all_ready": all(row["ready"] for row in scenarios),
        "scenario_count": len(scenarios),
        "scenarios": scenarios,
        "runtime_ml_control": "disabled_teacher_policy_validation_only",
    }


def build_manifest(config: dict[str, Any], report: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": "bot_validation_provisioning_manifest_v1",
        "config_hash": stable_hash(config),
        "scenario_count": len(config["scenarios"]),
        "bot_count": sum(len(scenario["bots"]) for scenario in config["scenarios"]),
        "outputs": {
            "account_commands": "account_commands.txt",
            "account_sql": "provision_accounts.sql",
            "provision_sql": "provision_characters.sql",
            "readiness_report": "report.json",
        },
        "all_ready": report["all_ready"],
        "runtime_ml_control": "disabled_teacher_policy_validation_only",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build reproducible prepared-character provisioning artifacts for bot validation scenarios.")
    parser.add_argument("--config", type=Path, default=Path("experiments/configs/validation_provisioning_cata_001.json"))
    parser.add_argument("--gear-profiles", type=Path, default=Path("dataset/validation_gear_profiles/profiles.json"))
    parser.add_argument("--output-dir", type=Path, default=Path("dataset/validation_provisioning"))
    args = parser.parse_args()

    config = apply_gear_profiles(load_config(args.config), load_gear_profiles(args.gear_profiles))
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "account_commands.txt").write_text(account_commands(config), encoding="utf-8")
    (args.output_dir / "provision_accounts.sql").write_text(build_account_insert_sql(config), encoding="utf-8")
    (args.output_dir / "provision_characters.sql").write_text(build_character_insert_sql(config), encoding="utf-8")
    report = scenario_report(config)
    write_json(args.output_dir / "report.json", report)
    write_json(args.output_dir / "manifest.json", build_manifest(config, report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
