from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

try:
    from .common import read_jsonl, stable_hash, write_json
except ImportError:
    from common import read_jsonl, stable_hash, write_json


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def load_scenarios(path: Path) -> list[dict[str, Any]]:
    return read_jsonl(path / "validation_scenarios.jsonl")


def scenario_output_name(scenario_id: str) -> str:
    return scenario_id.replace("/", "_").replace(" ", "_")


def live_validate_command(scenario: dict[str, Any], output_root: Path, observe_sec: int, timeout_sec: int) -> list[str]:
    scenario_id = str(scenario.get("scenario_id") or "")
    output_dir = output_root / scenario_output_name(scenario_id)
    return [
        "pixi",
        "run",
        "bot-live-validate",
        "--apply-validation-provisioning",
        "--reset-bot-pool",
        "--bot-pool-tag",
        scenario_id,
        "--keep-bot-pool-position",
        "--observe-sec",
        str(observe_sec),
        "--timeout-sec",
        str(timeout_sec),
        "--output-dir",
        str(output_dir),
    ]


def scenario_report_command(scenario: dict[str, Any], output_root: Path, report_root: Path, validation_scenario_dir: Path) -> list[str]:
    scenario_id = str(scenario.get("scenario_id") or "")
    return [
        "pixi",
        "run",
        "bot-live-scenario-reports",
        "--live-report",
        str(output_root / scenario_output_name(scenario_id) / "report.json"),
        "--validation-scenario-dir",
        str(validation_scenario_dir),
        "--scenario-id",
        scenario_id,
        "--output-dir",
        str(report_root),
    ]


def render_command(command: list[str]) -> str:
    return " ".join(shell_quote(part) for part in command)


def build_plan(scenarios: list[dict[str, Any]], output_root: Path, report_root: Path, validation_scenario_dir: Path, observe_sec: int, timeout_sec: int) -> dict[str, Any]:
    rows = []
    for scenario in sorted(scenarios, key=lambda row: str(row.get("scenario_id") or "")):
        scenario_id = str(scenario.get("scenario_id") or "")
        if not scenario_id:
            continue
        live_command = live_validate_command(scenario, output_root, observe_sec, timeout_sec)
        report_command = scenario_report_command(scenario, output_root, report_root, validation_scenario_dir)
        rows.append(
            {
                "scenario_id": scenario_id,
                "instance": scenario.get("instance") or "",
                "map_id": int(scenario.get("map_id") or 0),
                "difficulty": scenario.get("difficulty") or "",
                "required_roles": scenario.get("required_roles") or {},
                "live_output_dir": str(output_root / scenario_output_name(scenario_id)),
                "scenario_report_dir": str(report_root),
                "preserve_start_position": True,
                "bot_pool_tag": scenario_id,
                "live_validate_command": live_command,
                "scenario_report_command": report_command,
                "live_validate_shell": render_command(live_command),
                "scenario_report_shell": render_command(report_command),
            }
        )
    return {
        "schema": "bot_validation_run_plan_v1",
        "scenario_count": len(rows),
        "scenarios": rows,
        "runtime_ml_control": "disabled_until_live_clear_validation_passes",
        "plan_hash": stable_hash(rows),
    }


def write_shell_script(path: Path, plan: dict[str, Any]) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by tools.bot_ml.build_validation_run_plan.",
    ]
    for scenario in plan.get("scenarios") or []:
        lines.extend(
            [
                "",
                f"# {scenario['scenario_id']} - {scenario.get('instance', '')}",
                scenario["live_validate_shell"],
                scenario["scenario_report_shell"],
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o755)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build reproducible live validation run commands for Stonecore/BWD scenarios.")
    parser.add_argument("--validation-scenario-dir", type=Path, default=Path("dataset/validation_scenarios"))
    parser.add_argument("--output-dir", type=Path, default=Path("dataset/validation_run_plan"))
    parser.add_argument("--live-output-root", type=Path, default=Path("dataset/live_validation_scenarios"))
    parser.add_argument("--scenario-report-root", type=Path, default=Path("dataset/live_validation_scenario_reports_built"))
    parser.add_argument("--observe-sec", type=int, default=300)
    parser.add_argument("--timeout-sec", type=int, default=900)
    args = parser.parse_args()

    plan = build_plan(load_scenarios(args.validation_scenario_dir), args.live_output_root, args.scenario_report_root, args.validation_scenario_dir, args.observe_sec, args.timeout_sec)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    write_json(args.output_dir / "manifest.json", plan)
    write_shell_script(args.output_dir / "run_validation_scenarios.sh", plan)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
