from __future__ import annotations

import argparse
import base64
import html
import json
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any
from urllib.parse import urlparse
import re

try:
    from .build_validation_provisioning import apply_gear_profiles, build_account_insert_sql, build_character_insert_sql, load_config, load_gear_profiles
    from .common import write_json
    from .extract_world_knowledge import connect_mysql, database_url_from_worldserver_conf, sanitize_database_url
except ImportError:
    from build_validation_provisioning import apply_gear_profiles, build_account_insert_sql, build_character_insert_sql, load_config, load_gear_profiles
    from common import write_json
    from extract_world_knowledge import connect_mysql, database_url_from_worldserver_conf, sanitize_database_url


DEFAULT_STAGES = [
    "movement_smoke",
    "kill_quest",
    "collect_quest",
    "quest_hub_batching",
    "trainer_visit",
    "vendor_repair",
    "profession_recipe_acquisition",
    "material_farming",
    "smart_loot",
    "normal_dungeon_trash",
    "dungeon_boss",
    "full_stonecore_clear",
    "raid_trash",
    "raid_boss",
    "full_blackwing_descent_clear",
]

BOT_MEMORY_TABLES = [
    "bot_memory_daily_cooldowns",
    "bot_memory_danger_zones",
    "bot_memory_decision_fingerprints",
    "bot_memory_failed_paths",
    "bot_memory_material_sources",
    "bot_memory_objective_clusters",
    "bot_memory_pois",
    "bot_memory_recipe_sources",
    "bot_memory_safe_positions",
    "bot_memory_transport_usage",
]


def sql_quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def database_name(database_url: str) -> str:
    return (urlparse(database_url).path or "/").lstrip("/")


def trinity_config_bool(path: Path, key: str, default: bool = False) -> bool:
    if not path.exists():
        return default
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=\s*(?P<value>[^\s#]+)", re.MULTILINE)
    match = pattern.search(path.read_text(encoding="utf-8"))
    if not match:
        return default
    value = match.group("value").strip().strip('"').lower()
    if value in {"1", "true", "yes", "on"}:
        return True
    if value in {"0", "false", "no", "off"}:
        return False
    return default


def split_sql_statements(sql: str) -> list[str]:
    statements: list[str] = []
    current: list[str] = []
    quote: str | None = None
    escaped = False
    uncommented = "\n".join(line for line in sql.splitlines() if not line.lstrip().startswith("--"))
    for char in uncommented:
        current.append(char)
        if escaped:
            escaped = False
            continue
        if quote and char == "\\":
            escaped = True
            continue
        if char in {"'", '"'}:
            if quote == char:
                quote = None
            elif quote is None:
                quote = char
        elif char == ";" and quote is None:
            text = "".join(current).strip().rstrip(";").strip()
            if text and not text.startswith("--"):
                statements.append(text)
            current = []
    tail = "".join(current).strip()
    if tail:
        statements.append(tail)
    return statements


def execute_sql_text(database_url: str, sql: str) -> int:
    statements = split_sql_statements(sql)
    conn = connect_mysql(database_url)
    try:
        with conn.cursor() as cursor:
            for statement in statements:
                cursor.execute(statement)
        conn.commit()
    finally:
        conn.close()
    return len(statements)


def tag_predicate(tags: list[str]) -> str:
    if not tags:
        return "1 = 1"
    return "(" + " OR ".join(f"p.`experiment_tags` LIKE {sql_quote('%' + tag + '%')}" for tag in tags) + ")"


def build_bot_pool_reset_sql(tags: list[str] | None = None, world_database: str = "world", reset_positions: bool = True, reset_quests: bool = True, reset_memory: bool = True) -> str:
    tags = tags or ["test_account"]
    predicate = tag_predicate(tags)
    guid_select = f"SELECT p.`guid` FROM `characters`.`character_bot_pool` p WHERE p.`enabled` = 1 AND {predicate}"
    lines = [
        "-- Generated by tools.bot_ml.run_live_bot_validation.",
        "-- Resets only enabled bot-pool rows matching the configured experiment_tags predicate.",
        "UPDATE `characters`.`character_bot_pool` p SET p.`in_use` = 0 WHERE p.`enabled` = 1 AND " + predicate + ";",
        "UPDATE `characters`.`characters` c JOIN `characters`.`character_bot_pool` p ON p.`guid` = c.`guid` SET c.`online` = 0 WHERE p.`enabled` = 1 AND " + predicate + ";",
    ]
    if reset_positions:
        lines.append(
            "UPDATE `characters`.`characters` c "
            "JOIN `characters`.`character_bot_pool` p ON p.`guid` = c.`guid` "
            f"JOIN `{world_database}`.`playercreateinfo` pci ON pci.`race` = c.`race` AND pci.`class` = c.`class` "
            "SET c.`map` = pci.`map`, c.`position_x` = pci.`position_x`, c.`position_y` = pci.`position_y`, c.`position_z` = pci.`position_z`, c.`orientation` = pci.`orientation`, c.`health` = 100, c.`power1` = 100 "
            "WHERE p.`enabled` = 1 AND "
            + predicate
            + ";"
        )
    if reset_quests:
        for table in [
            "character_queststatus",
            "character_queststatus_daily",
            "character_queststatus_monthly",
            "character_queststatus_rewarded",
            "character_queststatus_seasonal",
            "character_queststatus_weekly",
            "character_aura",
            "character_spell_cooldown",
        ]:
            lines.append(f"DELETE FROM `characters`.`{table}` WHERE `guid` IN ({guid_select});")
    if reset_memory:
        for table in BOT_MEMORY_TABLES:
            lines.append(f"DELETE FROM `characters`.`{table}` WHERE `bot_guid` IN ({guid_select});")
    return "\n".join(lines) + "\n"


def prepare_validation_provisioning(
    output_dir: Path,
    config_path: Path,
    gear_profiles_path: Path,
    worldserver_conf: Path,
    apply: bool = False,
) -> dict[str, Any]:
    config = apply_gear_profiles(load_config(config_path), load_gear_profiles(gear_profiles_path))
    account_sql = build_account_insert_sql(config)
    character_sql = build_character_insert_sql(config)
    provision_dir = output_dir / "validation_provisioning_apply"
    provision_dir.mkdir(parents=True, exist_ok=True)
    account_path = provision_dir / "provision_accounts.sql"
    character_path = provision_dir / "provision_characters.sql"
    account_path.write_text(account_sql, encoding="utf-8")
    character_path.write_text(character_sql, encoding="utf-8")

    auth_url = database_url_from_worldserver_conf(worldserver_conf, "LoginDatabaseInfo")
    character_url = database_url_from_worldserver_conf(worldserver_conf, "CharacterDatabaseInfo")
    report: dict[str, Any] = {
        "schema": "bot_live_validation_provisioning_apply_v1",
        "applied": apply,
        "config": str(config_path),
        "gear_profiles": str(gear_profiles_path),
        "account_sql": str(account_path),
        "character_sql": str(character_path),
        "auth_database": sanitize_database_url(auth_url),
        "character_database": sanitize_database_url(character_url),
        "account_statement_count": len(split_sql_statements(account_sql)),
        "character_statement_count": len(split_sql_statements(character_sql)),
    }
    if apply:
        report["executed_account_statements"] = execute_sql_text(auth_url, account_sql)
        report["executed_character_statements"] = execute_sql_text(character_url, character_sql)
    return report


def prepare_bot_pool_reset(
    output_dir: Path,
    worldserver_conf: Path,
    tags: list[str],
    apply: bool = False,
    reset_positions: bool = True,
    reset_quests: bool = True,
    reset_memory: bool = True,
) -> dict[str, Any]:
    world_url = database_url_from_worldserver_conf(worldserver_conf, "WorldDatabaseInfo")
    character_url = database_url_from_worldserver_conf(worldserver_conf, "CharacterDatabaseInfo")
    sql = build_bot_pool_reset_sql(tags, database_name(world_url), reset_positions, reset_quests, reset_memory)
    reset_dir = output_dir / "bot_pool_reset"
    reset_dir.mkdir(parents=True, exist_ok=True)
    sql_path = reset_dir / "reset_bot_pool.sql"
    sql_path.write_text(sql, encoding="utf-8")
    report: dict[str, Any] = {
        "schema": "bot_live_validation_bot_pool_reset_v1",
        "applied": apply,
        "tags": tags,
        "reset_positions": reset_positions,
        "reset_quests": reset_quests,
        "reset_memory": reset_memory,
        "sql": str(sql_path),
        "statement_count": len(split_sql_statements(sql)),
        "world_database": sanitize_database_url(world_url),
        "character_database": sanitize_database_url(character_url),
    }
    if apply:
        report["executed_statements"] = execute_sql_text(character_url, sql)
    return report


def command_script(selector: str = "all", trace_limit: int = 20, start: bool = True, stop: bool = False, exit_server: bool = True) -> str:
    commands: list[str] = []
    if start:
        commands.append(".botauto start")
    commands.extend(
        [
            ".botauto status",
            f".botauto diagnose {selector}",
            f".botauto trace {selector} {trace_limit}",
            ".botexp summary",
        ]
    )
    if stop:
        commands.append(".botauto stop")
    if exit_server:
        commands.append("server shutdown force 0")
    return "\n".join(commands) + "\n"


def parse_json_objects(output: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line in output.splitlines():
        text = line.strip()
        if not text:
            continue
        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end == -1 or end <= start:
            continue
        try:
            payload = json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            continue
        if isinstance(payload, dict):
            rows.append(payload)
    return rows


def classify_payloads(payloads: list[dict[str, Any]]) -> dict[str, Any]:
    status = next((row for row in payloads if row.get("action") in {"botexp_status", "botauto_status"} or {"active", "active_bots", "target_bots"} & set(row)), {})
    diagnosis = next((row for row in payloads if row.get("diagnosis_schema_version") or row.get("diagnoses") or row.get("diagnosis")), {})
    trace = next((row for row in payloads if row.get("trace_schema_version") or row.get("entries")), {})
    summary = next((row for row in payloads if row.get("summary_schema_version") or "duration_minutes" in row or "total_kills" in row or "bot_learning" in row), {})
    return {"status": status, "diagnosis": diagnosis, "trace": trace, "summary": summary}


def command_errors(output: str) -> list[dict[str, str]]:
    errors: list[dict[str, str]] = []
    current_command = ""
    for line in output.splitlines():
        text = line.strip()
        if text.startswith("$ "):
            current_command = text[2:]
        elif "There is no such subcommand" in text:
            errors.append({"command": current_command, "error": "no_such_subcommand"})
    return errors


def should_observe_before_command(command_text: str) -> bool:
    return (
        command_text == ".botauto status"
        or command_text.startswith(".botauto diagnose")
        or command_text.startswith(".botauto trace")
        or command_text == ".botexp summary"
    )


def count_trace_entries(trace: dict[str, Any]) -> int:
    entries = trace.get("entries")
    if isinstance(entries, list):
        return len(entries)
    bots = trace.get("bots")
    if isinstance(bots, list):
        return sum(len(bot.get("entries") or []) for bot in bots if isinstance(bot, dict))
    return 0


def trace_entries(trace: dict[str, Any]) -> list[dict[str, Any]]:
    entries = trace.get("entries")
    if isinstance(entries, list):
        return [entry for entry in entries if isinstance(entry, dict)]
    bots = trace.get("bots")
    if isinstance(bots, list):
        rows: list[dict[str, Any]] = []
        for bot in bots:
            if isinstance(bot, dict):
                rows.extend(entry for entry in bot.get("entries") or [] if isinstance(entry, dict))
        return rows
    return []


def diagnosis_rows(diagnosis: dict[str, Any]) -> list[dict[str, Any]]:
    rows = diagnosis.get("diagnoses") or diagnosis.get("bots") or ([] if not diagnosis else [diagnosis])
    return [row for row in rows if isinstance(row, dict)]


def load_scenario_reports(path: Path | None) -> dict[str, dict[str, Any]]:
    if not path or not path.exists():
        return {}
    files = [path] if path.is_file() else sorted(path.glob("*.json"))
    reports: dict[str, dict[str, Any]] = {}
    for report_path in files:
        try:
            payload = json.loads(report_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(payload, dict):
            continue
        scenario_id = str(payload.get("scenario_id") or payload.get("id") or report_path.stem)
        if scenario_id:
            reports[scenario_id] = payload
    return reports


def nested_get(row: dict[str, Any], path: list[str], default: Any = None) -> Any:
    value: Any = row
    for key in path:
        if not isinstance(value, dict):
            return default
        value = value.get(key)
    return default if value is None else value


def scenario_bool(report: dict[str, Any], *keys: str) -> bool:
    return any(bool(report.get(key)) for key in keys)


def scenario_int(report: dict[str, Any], *keys: str) -> int:
    values = []
    for key in keys:
        try:
            values.append(int(report.get(key) or 0))
        except (TypeError, ValueError):
            values.append(0)
    return max(values or [0])


def scenario_group_ready(report: dict[str, Any]) -> bool:
    return scenario_bool(report, "prepared_group", "group_ready", "provisioning_ready")


def scenario_trash_ready(report: dict[str, Any]) -> bool:
    return scenario_bool(report, "trash_cleared", "trash_passed") or scenario_int(report, "trash_pulls", "trash_kills", "trash_packs_cleared") > 0


def scenario_boss_kills(report: dict[str, Any]) -> int:
    return scenario_int(report, "boss_kills", "raid_boss_kills", "bosses_killed")


def scenario_clear_complete(report: dict[str, Any]) -> bool:
    return scenario_bool(report, "clear_complete", "all_passed", "scenario_passed")


def scenario_missing(report: dict[str, Any], missing_name: str) -> list[str]:
    return [] if report else [missing_name]


def scenario_stage_missing(stage: str, scenario_reports: dict[str, dict[str, Any]]) -> list[str]:
    stonecore = scenario_reports.get("stonecore_5n") or {}
    bwd = scenario_reports.get("blackwing_descent_10n") or {}
    if stage == "normal_dungeon_trash":
        missing = scenario_missing(stonecore, "stonecore_live_clear_report")
        if stonecore and not scenario_group_ready(stonecore):
            missing.append("prepared_5man_group")
        if stonecore and not scenario_trash_ready(stonecore):
            missing.append("dungeon_trash_evidence")
        return missing
    if stage == "dungeon_boss":
        missing = scenario_missing(stonecore, "stonecore_live_clear_report")
        if stonecore and not scenario_group_ready(stonecore):
            missing.append("prepared_5man_group")
        if stonecore and scenario_boss_kills(stonecore) <= 0:
            missing.append("dungeon_boss_kill_evidence")
        return missing
    if stage == "full_stonecore_clear":
        missing = scenario_missing(stonecore, "stonecore_live_clear_report")
        if stonecore and not scenario_group_ready(stonecore):
            missing.append("prepared_5man_group")
        if stonecore and not scenario_clear_complete(stonecore):
            missing.append("stonecore_full_clear_evidence")
        return missing
    if stage == "raid_trash":
        missing = scenario_missing(bwd, "blackwing_descent_live_clear_report")
        if bwd and not scenario_group_ready(bwd):
            missing.append("prepared_10man_raid")
        if bwd and not scenario_trash_ready(bwd):
            missing.append("raid_trash_evidence")
        return missing
    if stage == "raid_boss":
        missing = scenario_missing(bwd, "blackwing_descent_live_boss_report")
        if bwd and not scenario_group_ready(bwd):
            missing.append("prepared_10man_raid")
        if bwd and scenario_boss_kills(bwd) <= 0:
            missing.append("raid_boss_kill_evidence")
        return missing
    if stage == "full_blackwing_descent_clear":
        missing = scenario_missing(bwd, "blackwing_descent_live_clear_report")
        if bwd and not scenario_group_ready(bwd):
            missing.append("prepared_10man_raid")
        if bwd and not scenario_clear_complete(bwd):
            missing.append("blackwing_descent_full_clear_evidence")
        return missing
    return []


def live_evidence(status: dict[str, Any], diagnosis: dict[str, Any], trace: dict[str, Any], summary: dict[str, Any]) -> dict[str, Any]:
    entries = trace_entries(trace)
    diagnoses = diagnosis_rows(diagnosis)
    non_spawn_trace_entries = sum(1 for entry in entries if str(entry.get("action") or entry.get("situation") or "") != "bot_spawned")
    decisions = max(int(status.get("decisions") or 0), int(summary.get("decisions") or 0), non_spawn_trace_entries)
    failures = max(int(status.get("failures") or 0), int(summary.get("failures_recorded") or 0))
    duration_seconds = int(status.get("duration_seconds") or 0)
    duration_minutes = float(summary.get("duration_minutes") or 0.0)
    moved_diagnoses = sum(1 for row in diagnoses if bool(nested_get(row, ["snapshot", "movement", "is_moving"], False)) or float(nested_get(row, ["snapshot", "movement", "distance_moved_since_last_decision"], 0) or 0) > 0.0)
    non_wait_diagnoses = sum(1 for row in diagnoses if str(nested_get(row, ["snapshot", "decision", "action"], "wait")) not in {"", "wait"})
    action_names = {
        str(entry.get("action") or entry.get("situation") or "")
        for entry in entries
        if entry.get("action") or entry.get("situation")
    }
    quest_acceptance_actions = sum(
        1
        for entry in entries
        if str(entry.get("action") or "").startswith("accept_quest") or str(entry.get("action") or "") == "accept_hub_quests"
    )
    quest_completion_actions = sum(
        1
        for entry in entries
        if str(entry.get("action") or "").startswith("complete_quest")
    )
    hub_acceptance_actions = sum(1 for entry in entries if str(entry.get("action") or "") == "accept_hub_quests")
    teacher_assisted_kills = sum(
        1
        for entry in entries
        if str(entry.get("action") or "") == "teacher_kill_assist"
        and str(entry.get("result") or "") == "simple_open_world_quest_mob_target"
    )
    action_names.update(
        str(nested_get(row, ["snapshot", "decision", "action"], ""))
        for row in diagnoses
        if nested_get(row, ["snapshot", "decision", "action"], "")
    )
    action_text = " ".join(sorted(action_names)).lower()
    quest_progress = max(int(status.get("quest_objective_progress") or 0), int(summary.get("quest_objective_progress") or 0))
    quests_accepted = max(int(status.get("quests_accepted") or 0), int(summary.get("quests_accepted") or 0), quest_acceptance_actions)
    quests_completed = max(int(status.get("quests_completed") or 0), int(summary.get("quests_completed") or 0), quest_completion_actions)
    kills = max(int(status.get("kills") or 0), int(summary.get("total_kills") or 0))
    kill_evidence = kills + teacher_assisted_kills
    gear_upgrades = max(int(status.get("gear_upgrades") or 0), int(summary.get("gear_upgrades") or 0))
    active_decision_evidence = decisions > 0 or non_spawn_trace_entries > 0 or moved_diagnoses > 0 or non_wait_diagnoses > 0
    return {
        "decisions": decisions,
        "failures": failures,
        "duration_seconds": duration_seconds,
        "duration_minutes": duration_minutes,
        "moved_diagnoses": moved_diagnoses,
        "non_wait_diagnoses": non_wait_diagnoses,
        "non_spawn_trace_entries": non_spawn_trace_entries,
        "quest_objective_progress": quest_progress,
        "quests_accepted": quests_accepted,
        "quests_completed": quests_completed,
        "hub_acceptance_actions": hub_acceptance_actions,
        "kills": kills,
        "teacher_assisted_kills": teacher_assisted_kills,
        "kill_evidence": kill_evidence,
        "gear_upgrades": gear_upgrades,
        "action_names": sorted(action_names),
        "vendor_or_trainer_action": any(token in action_text for token in ["vendor", "repair", "train"]),
        "profession_action": any(token in action_text for token in ["profession", "recipe", "craft"]),
        "material_farming_action": any(token in action_text for token in ["material", "farm", "gather", "herb", "mine", "skin"]),
        "loot_action": any(token in action_text for token in ["loot", "roll", "gear_upgrade"]),
        "active_decision_evidence": active_decision_evidence,
    }


def live_validation_report(output: str, stages: list[str] | None = None, returncode: int = 0, timed_out: bool = False, command: list[str] | None = None, scenario_reports: dict[str, dict[str, Any]] | None = None) -> dict[str, Any]:
    payloads = parse_json_objects(output)
    classified = classify_payloads(payloads)
    errors = command_errors(output)
    diagnosis = classified["diagnosis"]
    trace = classified["trace"]
    status = classified["status"]
    summary = classified["summary"]

    active_bots = int(status.get("active_bots") or status.get("bots") or status.get("activeBots") or 0)
    target_bots = int(status.get("target_bots") or status.get("targetBots") or 0)
    trace_entries = count_trace_entries(trace)
    diagnosis_count = len(diagnosis_rows(diagnosis))
    evidence = live_evidence(status, diagnosis, trace, summary)
    scenario_reports = scenario_reports or {}

    stage_rows = []
    for stage in stages or DEFAULT_STAGES:
        missing: list[str] = []
        if stage in {"movement_smoke", "kill_quest", "collect_quest", "quest_hub_batching", "trainer_visit", "vendor_repair", "profession_recipe_acquisition", "material_farming", "smart_loot"}:
            if active_bots <= 0:
                missing.append("active_autonomy_bots")
            if not diagnosis:
                missing.append("botauto_diagnose_json")
            if trace_entries <= 0:
                missing.append("botauto_trace_entries")
            if not evidence["active_decision_evidence"]:
                missing.append("active_decision_or_movement_evidence")
            if stage == "kill_quest" and evidence["kill_evidence"] <= 0:
                missing.append("kill_evidence")
            if stage in {"normal_dungeon_trash", "dungeon_boss"} and evidence["kills"] <= 0:
                missing.append("kill_evidence")
            if stage == "collect_quest" and evidence["quest_objective_progress"] <= 0 and evidence["quests_completed"] <= 0:
                missing.append("quest_progress_evidence")
            if stage == "quest_hub_batching" and evidence["quests_accepted"] <= 0:
                missing.append("quest_acceptance_evidence")
            if stage == "quest_hub_batching" and evidence["hub_acceptance_actions"] <= 0:
                missing.append("accept_hub_quests_action_evidence")
            if stage in {"trainer_visit", "vendor_repair"} and not evidence["vendor_or_trainer_action"]:
                missing.append("vendor_or_trainer_action_evidence")
            if stage == "profession_recipe_acquisition" and not evidence["profession_action"]:
                missing.append("profession_or_recipe_action_evidence")
            if stage == "material_farming" and not evidence["material_farming_action"]:
                missing.append("material_farming_action_evidence")
            if stage == "smart_loot" and evidence["gear_upgrades"] <= 0 and not evidence["loot_action"]:
                missing.append("loot_or_gear_upgrade_evidence")
        elif stage in {"normal_dungeon_trash", "dungeon_boss", "full_stonecore_clear", "raid_trash", "raid_boss", "full_blackwing_descent_clear"}:
            missing.extend(scenario_stage_missing(stage, scenario_reports))
        stage_rows.append({"stage": stage, "passed": not missing, "missing": missing})

    passed = sum(1 for row in stage_rows if row["passed"])
    return {
        "schema": "bot_live_validation_report_v1",
        "command": command or [],
        "returncode": returncode,
        "timed_out": timed_out,
        "json_payloads": len(payloads),
        "active_bots": active_bots,
        "target_bots": target_bots,
        "diagnosis_count": diagnosis_count,
        "trace_entries": trace_entries,
        "status": status,
        "diagnosis": diagnosis,
        "trace": trace,
        "summary": summary,
        "scenario_reports": scenario_reports,
        "command_errors": errors,
        "evidence": evidence,
        "stages": stage_rows,
        "passed": passed,
        "failed": len(stage_rows) - passed,
        "all_passed": passed == len(stage_rows),
        "runtime_ml_control": "disabled_until_live_validation_passes",
    }


def run_worldserver(binary: Path, config: Path, timeout_sec: int, script: str, observe_sec: int = 0) -> tuple[str, int, bool, list[str]]:
    command = [str(binary), "--config", str(config)]
    if observe_sec > 0:
        deadline = time.monotonic() + timeout_sec
        explicit_start = any(line.strip() == ".botauto start" for line in script.splitlines())
        observed_autostart = False
        process = subprocess.Popen(
            command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        assert process.stdin is not None
        try:
            for raw_command in script.splitlines():
                command_text = raw_command.strip()
                if not explicit_start and not observed_autostart and should_observe_before_command(command_text):
                    time.sleep(observe_sec)
                    observed_autostart = True
                process.stdin.write(raw_command + "\n")
                process.stdin.flush()
                if command_text == ".botauto start":
                    time.sleep(observe_sec)
                elif command_text.startswith("server shutdown") or command_text == "server exit":
                    shutdown_deadline = min(deadline, time.monotonic() + 10)
                    while process.poll() is None and time.monotonic() < shutdown_deadline:
                        time.sleep(0.25)
                    break
            if process.stdin and not process.stdin.closed:
                process.stdin.close()
                process.stdin = None
            remaining = max(1, int(deadline - time.monotonic()))
            output, _ = process.communicate(timeout=remaining)
            returncode = process.returncode if process.returncode is not None else 0
            return output, returncode, False, command
        except (BrokenPipeError, subprocess.TimeoutExpired) as exc:
            process.kill()
            output = (exc.stdout or "") if isinstance(exc, subprocess.TimeoutExpired) else ""
            if not output and process.stdout:
                output = process.stdout.read()
            return output, 124, True, command

    try:
        completed = subprocess.run(command, input=script, text=True, capture_output=True, timeout=timeout_sec, check=False)
        return completed.stdout + completed.stderr, completed.returncode, False, command
    except subprocess.TimeoutExpired as exc:
        output = (exc.stdout or "") + (exc.stderr or "")
        return output, 124, True, command


def soap_envelope(command: str) -> bytes:
    escaped = html.escape(command, quote=True)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:TC">'
        "<SOAP-ENV:Body>"
        f"<ns1:executeCommand><command>{escaped}</command></ns1:executeCommand>"
        "</SOAP-ENV:Body>"
        "</SOAP-ENV:Envelope>"
    ).encode("utf-8")


def parse_soap_result(payload: str) -> str:
    start = payload.find("<result>")
    end = payload.find("</result>")
    if start == -1 or end == -1 or end <= start:
        return payload
    return html.unescape(payload[start + len("<result>") : end])


def run_soap_commands(soap_url: str, username: str, password: str, script: str, timeout_sec: int, observe_sec: int = 0) -> tuple[str, int, bool, list[str]]:
    output_parts: list[str] = []
    auth = base64.b64encode(f"{username}:{password}".encode("utf-8")).decode("ascii")
    command = ["SOAP", soap_url]
    deadline = time.monotonic() + timeout_sec
    explicit_start = any(line.strip() == ".botauto start" for line in script.splitlines())
    observed_autostart = False
    for raw_command in script.splitlines():
        command_text = raw_command.strip()
        if not command_text:
            continue
        if observe_sec > 0 and not explicit_start and not observed_autostart and should_observe_before_command(command_text):
            output_parts.append(f"$ sleep {observe_sec}")
            time.sleep(observe_sec)
            observed_autostart = True
        remaining_float = deadline - time.monotonic()
        if remaining_float <= 0:
            return "\n".join(output_parts), 124, True, command
        remaining = max(1, int(remaining_float))
        request = urllib.request.Request(
            soap_url,
            data=soap_envelope(command_text),
            headers={
                "Authorization": f"Basic {auth}",
                "Content-Type": "text/xml; charset=utf-8",
                "SOAPAction": "urn:TC#executeCommand",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=remaining) as response:
                payload = response.read().decode("utf-8", errors="replace")
                output_parts.append(f"$ {command_text}")
                output_parts.append(parse_soap_result(payload))
                if observe_sec > 0 and command_text == ".botauto start":
                    output_parts.append(f"$ sleep {observe_sec}")
                    time.sleep(observe_sec)
        except urllib.error.HTTPError as exc:
            payload = exc.read().decode("utf-8", errors="replace")
            output_parts.append(f"$ {command_text}")
            output_parts.append(payload)
            return "\n".join(output_parts), exc.code, False, command
        except TimeoutError:
            return "\n".join(output_parts), 124, True, command
        except OSError as exc:
            output_parts.append(f"$ {command_text}")
            output_parts.append(str(exc))
            return "\n".join(output_parts), 1, False, command
    return "\n".join(output_parts), 0, False, command


def main() -> int:
    parser = argparse.ArgumentParser(description="Run or prepare live BotWorld validation diagnostics.")
    parser.add_argument("--worldserver", type=Path, default=Path("build/src/server/worldserver/worldserver"))
    parser.add_argument("--config", type=Path, default=Path("trinity-worldserver-test.conf"))
    parser.add_argument("--output-dir", type=Path, default=Path("dataset/live_validation"))
    parser.add_argument("--timeout-sec", type=int, default=90)
    parser.add_argument("--selector", default="all")
    parser.add_argument("--trace-limit", type=int, default=20)
    parser.add_argument("--no-start", action="store_true")
    parser.add_argument("--force-start-command", action="store_true", help="Send .botauto start even when BotWorld.AutoStart is enabled in the selected worldserver config.")
    parser.add_argument("--stop", action="store_true")
    parser.add_argument("--transport", choices=["process", "soap"], default="process")
    parser.add_argument("--soap-url", default="http://127.0.0.1:7878/")
    parser.add_argument("--soap-user")
    parser.add_argument("--soap-password")
    parser.add_argument("--observe-sec", type=int, default=0, help="Sleep after .botauto start before collecting diagnostics.")
    parser.add_argument("--reset-bot-pool", action="store_true", help="Before validation, reset volatile state for enabled bot-pool rows matching --bot-pool-tag.")
    parser.add_argument("--bot-pool-tag", action="append", default=[], help="Experiment tag substring for --reset-bot-pool. Defaults to test_account when omitted.")
    parser.add_argument("--keep-bot-pool-position", action="store_true", help="Do not move reset bot-pool characters back to race/class start positions.")
    parser.add_argument("--keep-bot-pool-quests", action="store_true", help="Do not clear quest/aura/cooldown state for reset bot-pool characters.")
    parser.add_argument("--keep-bot-pool-memory", action="store_true", help="Do not clear persistent bot memory tables for reset bot-pool characters.")
    parser.add_argument("--apply-validation-provisioning", action="store_true", help="Apply deterministic Stonecore/BWD validation account and character SQL before running diagnostics.")
    parser.add_argument("--validation-provisioning-config", type=Path, default=Path("experiments/configs/validation_provisioning_cata_001.json"))
    parser.add_argument("--gear-profiles", type=Path, default=Path("dataset/validation_gear_profiles/profiles.json"))
    parser.add_argument("--scenario-report-dir", type=Path, help="Optional directory or JSON file containing scenario live reports such as stonecore_5n.json and blackwing_descent_10n.json.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--input-log", type=Path)
    args = parser.parse_args()

    config_autostart = trinity_config_bool(args.config, "BotWorld.AutoStart", False)
    send_start_command = not args.no_start and (args.force_start_command or not config_autostart)
    script = command_script(selector=args.selector, trace_limit=args.trace_limit, start=send_start_command, stop=args.stop, exit_server=args.transport == "process")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "commands.txt").write_text(script, encoding="utf-8")
    bot_pool_tags = args.bot_pool_tag or ["test_account"]
    preparation: dict[str, Any] = {}
    scenario_reports = load_scenario_reports(args.scenario_report_dir)
    if args.reset_bot_pool:
        preparation["bot_pool_reset"] = prepare_bot_pool_reset(
            args.output_dir,
            args.config,
            bot_pool_tags,
            apply=not args.dry_run,
            reset_positions=not args.keep_bot_pool_position,
            reset_quests=not args.keep_bot_pool_quests,
            reset_memory=not args.keep_bot_pool_memory,
        )
    if args.apply_validation_provisioning:
        preparation["validation_provisioning"] = prepare_validation_provisioning(
            args.output_dir,
            args.validation_provisioning_config,
            args.gear_profiles,
            args.config,
            apply=not args.dry_run,
        )

    if args.dry_run:
        report = {
            "schema": "bot_live_validation_report_v1",
            "dry_run": True,
            "command_script": script,
            "worldserver": str(args.worldserver),
            "config": str(args.config),
            "transport": args.transport,
            "soap_url": args.soap_url if args.transport == "soap" else "",
            "timeout_sec": args.timeout_sec,
            "observe_sec": args.observe_sec,
            "config_autostart": config_autostart,
            "start_command": send_start_command,
            "preparation": preparation,
            "scenario_reports": scenario_reports,
            "instructions": "Run make host-world-botexp-small for attached diagnostics or execute this script without --dry-run when the worldserver binary and config are ready.",
        }
        write_json(args.output_dir / "report.json", report)
        print(json.dumps(report, indent=2, sort_keys=True))
        return 0

    if args.input_log:
        output = args.input_log.read_text(encoding="utf-8")
        returncode = 0
        timed_out = False
        command: list[str] = []
    else:
        if args.transport == "soap":
            if not args.soap_user or not args.soap_password:
                raise SystemExit("--soap-user and --soap-password are required with --transport soap")
            output, returncode, timed_out, command = run_soap_commands(args.soap_url, args.soap_user, args.soap_password, script, args.timeout_sec, args.observe_sec)
        else:
            output, returncode, timed_out, command = run_worldserver(args.worldserver, args.config, args.timeout_sec, script, args.observe_sec)

    (args.output_dir / "worldserver_output.log").write_text(output, encoding="utf-8")
    report = live_validation_report(output, returncode=returncode, timed_out=timed_out, command=command, scenario_reports=scenario_reports)
    report["generated_at_unix"] = int(time.time())
    report["config_autostart"] = config_autostart
    report["start_command"] = send_start_command
    report["preparation"] = preparation
    write_json(args.output_dir / "report.json", report)
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if returncode == 0 and not timed_out else 1


if __name__ == "__main__":
    raise SystemExit(main())
